### ISSUE TITLE
[Bug] Crashed when App was init from CupertinoApp.

### ISSUE THREAD

**Issue by wh1990xiao2005** [MariaMelnik/flutter_date_pickers#29]
Crashed when App was init from CupertinoApp.
Please refer the code below: 

```
import 'dart:io';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_date_pickers/flutter_date_pickers.dart';

import 'md.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Widget> testWidgets = new List();

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    DatePickerRangeStyles styles = DatePickerRangeStyles(
      selectedPeriodLastDecoration: BoxDecoration(
          color: Colors.red,
          borderRadius: BorderRadius.only(
              topRight: Radius.circular(10.0),
              bottomRight: Radius.circular(10.0))),
      selectedPeriodStartDecoration: BoxDecoration(
        color: Colors.green,
        borderRadius: BorderRadius.only(
            topLeft: Radius.circular(10.0), bottomLeft: Radius.circular(10.0)),
      ),
      selectedPeriodMiddleDecoration:
          BoxDecoration(color: Colors.yellow, shape: BoxShape.rectangle),
    );
    return CupertinoPageScaffold(
                child: WeekPicker(
                    selectedDate: DateTime.now(),
                    onChanged: (dateRange) {},
                    firstDate: DateTime.now().subtract(Duration(days: 10)),
                    lastDate: DateTime.now().add(Duration(minutes: 10)),
                    datePickerStyles: styles));
  }
}

```

Crash stack info below:

> The following NoSuchMethodError was thrown building WeekPicker(dirty, dependencies: [_LocalizationsScope-[GlobalKey#678bc]]):
The getter 'firstDayOfWeekIndex' was called on null.
Receiver: null
Tried calling: firstDayOfWeekIndex

> The relevant error-causing widget was: 
  WeekPicker file:///Users/wenhan/AndroidStudioProjects/flutter_hello/lib/main.dart:56:24
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      WeekPicker.build (package:flutter_date_pickers/src/week_picker.dart:88:64)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
...

**Please refer the fix solution:**
At **week_picker.dart**:

**original code**
```
  @override
  Widget build(BuildContext context){
    MaterialLocalizations localizations = MaterialLocalizations.of(context);
```

**Solution**

```
  @override
  Widget build(BuildContext context){
    var localizations;
    if(MaterialLocalizations.of(context) == null){
      localizations = CupertinoLocalizations.of(context);
    } else{
      localizations = MaterialLocalizations.of(context);
    }
```

Please refer suggest above, thank you.

**Comment by MariaMelnik** [comment]
@wh1990xiao2005 thank you for pointing that out. I fixed it in new release.
You can check if you change your dependency to:
```
dependencies:
  flutter_date_pickers: ^0.1.5
```

Don't hesitate to open this issue if you will find bug there.
